import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Nordic Citrus & Deep Navy System Tokens
        'surface-tint': '#0F172A',
        'on-tertiary-fixed-variant': '#FF5400',
        'surface-bright': '#FFFFFF',
        'surface-container-highest': '#CBD5E1',
        'on-error': '#FFFFFF',
        'on-tertiary-fixed': '#0F172A',
        'surface-variant': '#F1F5F9',
        'tertiary-fixed-dim': '#FFB703',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-high': '#E2E8F0',
        'on-primary-fixed': '#FFFFFF',
        'tertiary': '#FFB703',
        'secondary': '#FF5400',
        'background': '#F8FAFC',
        'on-primary-container': '#FFFFFF',
        'secondary-fixed': '#FFEADB',
        'error-container': '#FEE2E2',
        'on-secondary-fixed': '#7C2D12',
        'error': '#DC2626',
        'tertiary-fixed': '#FEF3C7',
        'inverse-primary': '#CBD5E1',
        'secondary-container': '#FFF0EA',
        'surface-container-low': '#F8FAFC',
        'primary': '#0F172A',
        'primary-fixed-dim': '#334155',
        'surface-dim': '#E2E8F0',
        'primary-container': '#0F172A',
        'on-error-container': '#7F1D1D',
        'on-tertiary': '#0F172A',
        'inverse-on-surface': '#F8FAFC',
        'on-primary-fixed-variant': '#64748B',
        'outline-variant': '#E2E8F0',
        'outline': '#94A3B8',
        'secondary-fixed-dim': '#FDBA74',
        'on-background': '#0F172A',
        'inverse-surface': '#0F172A',
        'surface-container': '#F1F5F9',
        'on-surface-variant': '#64748B',
        'tertiary-container': '#FFF8E6',
        'on-tertiary-container': '#78350F',
        'surface': '#FFFFFF',
        'on-surface': '#0F172A',
        'on-secondary-fixed-variant': '#9A3412',
        'on-secondary': '#FFFFFF',
        'on-primary': '#FFFFFF',
        'primary-fixed': '#E2E8F0',
        'on-secondary-container': '#9A3412',

        // Brand Palette
        citrus: {
          50: '#FFF7ED',
          100: '#FFEDD5',
          200: '#FED7AA',
          500: '#FF5400',
          600: '#EA4A00',
          700: '#C23D00',
        },
        navy: {
          50: '#F8FAFC',
          100: '#F1F5F9',
          200: '#E2E8F0',
          700: '#334155',
          800: '#1E293B',
          900: '#0F172A',
          950: '#0B0F19',
        },
        gold: {
          400: '#FACC15',
          500: '#FFB703',
          600: '#EAB308',
        },
        emerald: {
          500: '#10B981',
          600: '#059669',
          700: '#047857',
        },
      },
      spacing: {
        margin: '32px',
        xs: '4px',
        md: '16px',
        gutter: '24px',
        xl: '32px',
        lg: '24px',
        sm: '8px',
        base_unit: '8px'
      },
      fontFamily: {
        serif: ['var(--font-serif)', 'Playfair Display', 'Georgia', 'serif'],
        sans: ['var(--font-sans)', 'Geist', 'Inter', 'sans-serif'],
        'label-caps': ['Geist', 'Inter', 'sans-serif'],
        'headline-md': ['Geist', 'Inter', 'sans-serif'],
        'body-base': ['Geist', 'Inter', 'sans-serif'],
        'headline-sm': ['Geist', 'Inter', 'sans-serif'],
        'mono-data': ['Geist Mono', 'JetBrains Mono', 'monospace'],
        'display-lg': ['Geist', 'Playfair Display', 'serif'],
        'body-sm': ['Geist', 'Inter', 'sans-serif'],
      },
      fontSize: {
        'label-caps': ['11px', { lineHeight: '12px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-base': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'mono-data': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'display-lg': ['30px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }]
      },
      boxShadow: {
        'xs': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        '2xs': '0 1px 1px 0 rgba(0, 0, 0, 0.03)',
        'soft-card': '0 10px 30px -5px rgba(255, 84, 0, 0.08), 0 4px 12px rgba(0, 0, 0, 0.03)',
        'vibrant': '0 12px 35px -8px rgba(255, 84, 0, 0.25)',
        'floating': '0 25px 50px -12px rgba(15, 23, 42, 0.2)',
      }
    },
  },
  plugins: [],
};

export default config;
