import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Stitch MCP Theme Color Tokens
        'surface-tint': '#565e74',
        'on-tertiary-fixed-variant': '#574425',
        'surface-bright': '#fcf8fa',
        'surface-container-highest': '#e4e2e4',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#271901',
        'surface-variant': '#e4e2e4',
        'tertiary-fixed-dim': '#dec29a',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#eae7e9',
        'on-primary-fixed': '#131b2e',
        'tertiary': '#000000',
        'secondary': '#505f76',
        'background': '#fcf8fa',
        'on-primary-container': '#7c839b',
        'secondary-fixed': '#d3e4fe',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#0b1c30',
        'error': '#ba1a1a',
        'tertiary-fixed': '#fcdeb5',
        'inverse-primary': '#bec6e0',
        'secondary-container': '#d0e1fb',
        'surface-container-low': '#f6f3f5',
        'primary': '#000000',
        'primary-fixed-dim': '#bec6e0',
        'surface-dim': '#dcd9db',
        'primary-container': '#131b2e',
        'on-error-container': '#93000a',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#f3f0f2',
        'on-primary-fixed-variant': '#3f465c',
        'outline-variant': '#c6c6cd',
        'outline': '#76777d',
        'secondary-fixed-dim': '#b7c8e1',
        'on-background': '#1b1b1d',
        'inverse-surface': '#303032',
        'surface-container': '#f0edef',
        'on-surface-variant': '#45464d',
        'tertiary-container': '#271901',
        'on-tertiary-container': '#98805d',
        'surface': '#fcf8fa',
        'on-surface': '#1b1b1d',
        'on-secondary-fixed-variant': '#38485d',
        'on-secondary': '#ffffff',
        'on-primary': '#ffffff',
        'primary-fixed': '#dae2fd',
        'on-secondary-container': '#54647a',

        // Legacy & Brand Colors
        amber: {
          50: '#FFFBEB',
          100: '#FEF3C7',
          500: '#F59E0B',
          600: '#D97706',
          700: '#B45309',
        },
        orange: {
          500: '#F97316',
          600: '#EA580C',
          700: '#C2410C',
        },
        emerald: {
          500: '#10B981',
          600: '#059669',
          700: '#047857',
        },
        coral: {
          500: '#F43F5E',
          600: '#E11D48',
        },
        cream: {
          50: '#FAF9F6',
          100: '#F4F1EA',
          200: '#EAE5D9',
          300: '#DDD5C4',
          400: '#CBBBA7',
        },
        charcoal: {
          700: '#334155',
          800: '#1E293B',
          900: '#0F172A',
        },
        bronze: {
          500: '#D97706',
          600: '#B45309',
          700: '#92400E',
        },
      },
      spacing: {
        margin: '32px',
        xs: '4px',
        md: '16px',
        gutter: '24px',
        xl: '32px',
        lg: '24px',
        sm: '8px',
        base_unit: '8px'
      },
      fontFamily: {
        serif: ['var(--font-serif)', 'Playfair Display', 'Georgia', 'serif'],
        sans: ['var(--font-sans)', 'Geist', 'Inter', 'sans-serif'],
        'label-caps': ['Geist', 'Inter', 'sans-serif'],
        'headline-md': ['Geist', 'Inter', 'sans-serif'],
        'body-base': ['Geist', 'Inter', 'sans-serif'],
        'headline-sm': ['Geist', 'Inter', 'sans-serif'],
        'mono-data': ['Geist Mono', 'JetBrains Mono', 'monospace'],
        'display-lg': ['Geist', 'Playfair Display', 'serif'],
        'body-sm': ['Geist', 'Inter', 'sans-serif'],
      },
      fontSize: {
        'label-caps': ['11px', { lineHeight: '12px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-base': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'mono-data': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'display-lg': ['30px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }]
      },
      boxShadow: {
        'xs': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        '2xs': '0 1px 1px 0 rgba(0, 0, 0, 0.03)',
        'soft-card': '0 10px 30px -5px rgba(249, 115, 22, 0.08), 0 4px 12px rgba(0, 0, 0, 0.03)',
        'vibrant': '0 12px 35px -8px rgba(234, 88, 12, 0.25)',
        'floating': '0 25px 50px -12px rgba(15, 23, 42, 0.2)',
      }
    },
  },
  plugins: [],
};

export default config;
