# Generated by Django 5.2.17 on 2026-08-07 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOrder',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('avatar', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('item_count', models.IntegerField(default=1)),
                ('payment_method', models.CharField(default='Midtrans QRIS / GoPay', max_length=100)),
                ('payment_badge', models.CharField(choices=[('PAID', 'PAID'), ('AWAITING', 'AWAITING'), ('REFUNDED', 'REFUNDED'), ('FAILED', 'FAILED')], default='PAID', max_length=20)),
                ('delivery_type', models.CharField(default='Biaya Pengiriman Standard', max_length=100)),
                ('status', models.CharField(choices=[('RECEIVED', '1. Diterima'), ('COOKING', '2. Dimasak'), ('READY', '3. Siap'), ('DELIVERING', '4. Diantar'), ('COMPLETED', '5. Selesai'), ('CANCELLED', 'Dibatalkan')], default='COOKING', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdminVoucher',
            fields=[
                ('voucher_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('min_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('expiry', models.CharField(default='31 Des 2026', max_length=100)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('item_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(default='Makanan Utama', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('stock', models.IntegerField(default=50)),
                ('visibility', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Low Stock', 'Low Stock'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('rating', models.FloatField(default=4.9)),
                ('reviews_count', models.IntegerField(default=120)),
                ('sold_count', models.CharField(default='150 Terjual', max_length=50)),
                ('image', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('badge', models.CharField(blank=True, choices=[('TERPOPULER', 'TERPOPULER'), ('BARU', 'BARU'), ('BEST SELLER', 'BEST SELLER'), ('NEW', 'NEW')], max_length=20, null=True)),
                ('ingredients', models.TextField(blank=True, default='')),
                ('usage_advice', models.TextField(blank=True, default='')),
                ('calories', models.CharField(default='320 kcal', max_length=30)),
                ('fat', models.CharField(default='12g', max_length=30)),
                ('sugar', models.CharField(default='4g', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('review_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_badge', models.CharField(default='GOLD', max_length=50)),
                ('avatar', models.CharField(blank=True, max_length=500, null=True)),
                ('rating', models.IntegerField(default=5)),
                ('date', models.CharField(default='Kemarin', max_length=50)),
                ('product_name', models.CharField(max_length=150)),
                ('product_image', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField()),
                ('likes_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='PUBLISHED', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField(default=1)),
                ('image', models.CharField(max_length=500)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.adminorder')),
            ],
        ),
    ]
